# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9eea183e75442853ce64ee4f4b75ddd9d4c4d1b628c0f80f5e9b50f8d6823e95a84d95bb0ffdc30aefc8b4d54903b2a2a7a1bd91f44f52403540e46338eb909

test:
  secret_key_base: f184acff1ee05deac923f0e3c5b9738dc499296d66bdae377a37c83fb87d38f597c694189f2c2348e3fe430810aaf4b0d639f54645a921f067c970a52fd52ef8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
